/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iplanalysis;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;


import csvbuilder.CSVBuilderException;
import csvbuilder.CSVBuilderFactory;
import csvbuilder.ICSVBuilder;

import model.IPLDAO;


public class IPLDataLoader {
	
	public List<IPLDAO> iplDaoList = null;
	
	public IPLDataLoader() {
		iplDaoList = new ArrayList<>();

	}
	
	@SuppressWarnings({ "rawtypes", "unchecked" })
	public <E> List loadIPLData(Class<E> classType, String csvFilePath, char delimiter)
			throws CSVBuilderException {
		try (Reader reader = Files.newBufferedReader(Paths.get(csvFilePath))) {
			ICSVBuilder csvBuilder = CSVBuilderFactory.createCSVBuilder();
			Iterator<E> csvFileIterator = csvBuilder.getCSVFileIterator(reader, classType, delimiter);
			switch (classType.getSimpleName()) {
			case "IPLMostRuns":
				iplDaoList.clear();
				while (csvFileIterator.hasNext())
					this.iplDaoList.add(new IPLDAO((IPLMostRuns) csvFileIterator.next()));
				break;

			case "IPLMostWIckets":
				iplDaoList.clear();
				while (csvFileIterator.hasNext())
					this.iplDaoList.add(new IPLDAO((IPLMostWIckets) csvFileIterator.next()));
				break;
			}
			return iplDaoList;
		} catch (IOException e) {
			throw new CSVBuilderException(e.getMessage(), CSVBuilderException.ExceptionType.CENSUS_FILE_PROBLEM);
		}
	}
	
	
}
