/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iplanalysis;

import org.junit.Test;

import csvbuilder.CSVBuilderException;
import model.IPLDAO;

import static org.junit.Assert.*;

import java.util.List;

public class IPLTest {
	private static final String IPL_MOST_RUNS_CSV_FILE_PATH = "./src/test/resources/WP DP Data_01 IPL2019FactsheetMostRuns.csv";
	private static final String IPL_MOST_WICKETS_CSV_FILE_PATH = "./src/test/resources/WP DP Data_02 IPL2019FactsheetMostWkts.csv";
	@Test
	public void givenIPLCsv_WhenLoaded_ShouldReturnCount() {
		IPLDataLoader iplDataLoader = new IPLDataLoader();
		try {
			List<IPLDAO> mostRunsList = iplDataLoader.loadIPLData(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH, ',');
			List<IPLDAO> mostWktsList = iplDataLoader.loadIPLData(IPLMostWIckets.class, IPL_MOST_WICKETS_CSV_FILE_PATH, ',');
			assertEquals(101, mostRunsList.size());
			assertEquals(99, mostWktsList.size());
		} catch (CSVBuilderException e) {}
		
	}
}
