/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iplanalysis;

import org.junit.Test;

import com.google.gson.Gson;
import csvbuilder.CSVBuilderException;
import model.IPLDAO;

import static org.junit.Assert.*;

import java.util.List;

public class IPLTest {
	private static final String IPL_MOST_RUNS_CSV_FILE_PATH = "./src/test/resources/WP DP Data_01 IPL2019FactsheetMostRuns.csv";
	private static final String IPL_MOST_WICKETS_CSV_FILE_PATH = "./src/test/resources/WP DP Data_02 IPL2019FactsheetMostWkts.csv";

	@Test
	public void givenIPLCsv_WhenLoaded_ShouldReturnCount() {
		IPLDataLoader iplDataLoader = new IPLDataLoader();
		try {
			List<IPLDAO> mostRunsList = iplDataLoader.loadIPLData(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH, ',');
			List<IPLDAO> mostWktsList = iplDataLoader.loadIPLData(IPLMostWIckets.class, IPL_MOST_WICKETS_CSV_FILE_PATH,
					',');
			assertEquals(99, mostRunsList.size());
			assertEquals(99, mostWktsList.size());
		} catch (CSVBuilderException e) {
		}

	}

	@Test
	public void givenIPLCsv_WhenSortedAverageWise_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getAverageWiseSortedIPLMostRunsData();
			IPLMostRuns[] mostRunsCsv = new Gson().fromJson(sortedIplData, IPLMostRuns[].class);
			assertEquals("MS Dhoni", mostRunsCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLCsv_WhenSortedStrikeRateWise_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getStrikeRatesWiseSortedIPLMostRunsData();
			IPLMostRuns[] mostRunsCsv = new Gson().fromJson(sortedIplData, IPLMostRuns[].class);
			assertEquals("Ishant Sharma", mostRunsCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLCsv_WhenSortedFoursandSixesWise_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getFoursandSixesWiseSortedIPLMostRunsData();
			IPLMostRuns[] mostRunsCsv = new Gson().fromJson(sortedIplData, IPLMostRuns[].class);
			assertEquals("Andre Russell", mostRunsCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLCsv_WhenSortedbasedOnStrikeRateFoursandSixesWise_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getStrinkeRateFoursandSixesWiseSortedIPLMostRunsData();
			IPLMostRuns[] mostRunsCsv = new Gson().fromJson(sortedIplData, IPLMostRuns[].class);
			assertEquals("Ishant Sharma", mostRunsCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLCsv_WhenSortedbasedOnAverageandStrikeRate_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getAverageandStrikeRateWiseSortedIPLMostRunsData();
			IPLMostRuns[] mostRunsCsv = new Gson().fromJson(sortedIplData, IPLMostRuns[].class);
			assertEquals("MS Dhoni", mostRunsCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLCsv_WhenSortedbasedOnMaximumRunsandBestAverage_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getMaximumRunsandBestAverageWiseSortedIPLMostRunsData();
			IPLMostRuns[] mostRunsCsv = new Gson().fromJson(sortedIplData, IPLMostRuns[].class);

			assertEquals("Jonny Bairstow", mostRunsCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLWicketCsv_WhenSortedbasedOnBowlingAverage_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostWIckets.class, IPL_MOST_WICKETS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getBowlingAverageWiseSortedIPLMostWicketsData();
			IPLDAO[] mostWicketsCsv = new Gson().fromJson(sortedIplData, IPLDAO[].class);
			assertEquals("Krishnappa Gowtham", mostWicketsCsv[0].playerBowler);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLWicketCsv_WhenSortedbasedOnStrikeRate_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostWIckets.class, IPL_MOST_WICKETS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getStrikeRatesWiseSortedIPLMostRunsData();
			IPLDAO[] mostWicketsCsv = new Gson().fromJson(sortedIplData, IPLDAO[].class);
			assertEquals("Imran Tahir", mostWicketsCsv[0].playerBowler);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLWicketCsv_WhenSortedbasedOnEconomyRate_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostWIckets.class, IPL_MOST_WICKETS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getBowlingEconomyRateWiseSortedIPLMostWicketsData();
			IPLDAO[] mostWicketsCsv = new Gson().fromJson(sortedIplData, IPLDAO[].class);
			assertEquals("Ben Cutting", mostWicketsCsv[0].playerBowler);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLWicketCsv_WhenSortedbasedOnSTrikeRate4Wand5W_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostWIckets.class, IPL_MOST_WICKETS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getStrikeRateWith4Wand5WWiseSortedIPLMostWicketsData();
			IPLDAO[] mostWicketsCsv = new Gson().fromJson(sortedIplData, IPLDAO[].class);
			assertEquals("Krishnappa Gowtham", mostWicketsCsv[0].playerBowler);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLWicketCsv_WhenSortedbasedOnBowlingAverageandStrikeRate_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostWIckets.class, IPL_MOST_WICKETS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getBowlingAverageWithStrikeRateSortedIPLMostWicketsData();
			IPLDAO[] mostWicketsCsv = new Gson().fromJson(sortedIplData, IPLDAO[].class);
			assertEquals("Krishnappa Gowtham", mostWicketsCsv[0].playerBowler);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLWicketCsv_WhenSortedbasedOnWicketsandBowlingAverage_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostWIckets.class, IPL_MOST_WICKETS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getWicketsandBowlingAverageWiseSortedIPLMostWicketsData();
			IPLDAO[] mostWicketsCsv = new Gson().fromJson(sortedIplData, IPLDAO[].class);
			assertEquals("Imran Tahir", mostWicketsCsv[0].playerBowler);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void givenIPLWicketCsv_WhenSortedbasedOnBattingandBowlingAverage_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis();
			String sortedIplData = iplAnalysis.getBattingandBowlingAverageWiseSortedIPLMostData(IPLMostRuns.class,
					IPLMostWIckets.class, IPL_MOST_RUNS_CSV_FILE_PATH, IPL_MOST_WICKETS_CSV_FILE_PATH);
			IPLDAO[] sortedCsv = new Gson().fromJson(sortedIplData, IPLDAO[].class);
			assertEquals("Andre Russell", sortedCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}
	
	@Test
	public void givenIPLWicketCsv_WhenSortedbasedOnAllRounder_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis();
			String sortedIplData = iplAnalysis.getBestAllRounder(IPLMostRuns.class,
					IPLMostWIckets.class, IPL_MOST_RUNS_CSV_FILE_PATH, IPL_MOST_WICKETS_CSV_FILE_PATH);
			IPLDAO[] sortedCsv = new Gson().fromJson(sortedIplData, IPLDAO[].class);
			assertEquals("Hardik Pandya", sortedCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}
	
	
	@Test
	public void givenIPLCsv_WhenSortedbasedOnMaxCenturyandBestAverage_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getMaxCenturyandbattingAvgWiseSortedIPLMostRunsData();
			IPLMostRuns[] mostRunsCsv = new Gson().fromJson(sortedIplData, IPLMostRuns[].class);
			assertEquals("David Warner", mostRunsCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}
	
	@Test
	public void givenIPLCsv_WhenSortedbasedOnZero100sOr50sandBestAverage_ShouldReturnBest() {
		try {
			IPLAnalysis iplAnalysis = new IPLAnalysis(IPLMostRuns.class, IPL_MOST_RUNS_CSV_FILE_PATH);
			String sortedIplData = iplAnalysis.getBestBattingAvgWithZeroHundredsOrFifties();
			IPLMostRuns[] mostRunsCsv = new Gson().fromJson(sortedIplData, IPLMostRuns[].class);
			assertEquals("Marcus Stoinis", mostRunsCsv[0].player);
		} catch (CSVBuilderException e) {
			e.printStackTrace();
		}
	}
}
